version: "3.8"
   
services:
    db:
        image: postgres:12
        env_file: .env.dev
        volumes:
            - postgres_data:/var/lib/postgresql/data

    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
        links:
            - db:db
        env_file: .env.dev
    nginx:
        build: ./nginx
        ports:
            - 1337:80
        depends_on: 
            - web


volumes:
    postgres_data:
